### ISSUE TITLE
deep.Copy does not copy `any` type struct fields

### ISSUE THREAD

**Issue by matt-FFFFFF** [brunoga/deep#1]
Hi,

I am using your module to copy Azure policy types from the Azure Go SDK:

Specifically, the `armpolicy.DefinitionProperties`, which is embedded in an `armpolicy.Definition`

The definition is here:

https://github.com/Azure/azure-sdk-for-go/blob/4cfdce079727722cd149da6d9e3be9a059157a73/sdk/resourcemanager/resources/armpolicy/models.go#L288C1-L309C2

You see that there are two fields with type `any`. Metadata and PolicyRule. These fields are JSON unmarshaled into a map[string]interface{}.

These are not copied by the .Copy func, nor is there an error returned.

Debugging the issue, the recursive funcs seems to work, but this expression causes the field not to be assigned to the destination:

https://github.com/brunoga/deep/blob/4a49e06a0e13cfd53303002ed250eb71c0d66a06/deep.go#L204-L207

Commenting out the above fixes the issue but then the Interface_Nil test panics

See test in #2

**Comment by matt-FFFFFF** [comment]
@brunoga proposed a fix in #2 

All tests now pass

**Comment by brunoga** [comment]
Thanks for the report and the fix. I am reviewing it now.
