### ISSUE TITLE
Thank you for this library!

### ISSUE THREAD

**Issue by takanuva15** [brunoga/deep#3]
Just wanted to give a shout-out and a thank-you for making this awesome library. Was looking for something to easily deep copy nested arrays for my unit tests and this fit the bill perfectly. 

I originally found https://github.com/barkimedes/go-deepcopy through Google search, but it's dead (as you said in the README) and it doesn't work for arrays (bummer!). Hopefully your library rises above his in Google Search results for "Golang deep copy" soon haha! 🚀

**Comment by brunoga** [comment]
I was glad I was able to help. FWIIW, I am extending it sun to also add generating a diff between 2 structures and patching that diff on another one.
