### ISSUE TITLE
[FEATURE] CLI wrapper

### ISSUE THREAD

**Issue by s3rj1k** [brunoga/deep#4]
Please consider adding CLI wrapper so it would be possible to install and run deep-gen similar to the K8s tools

**Comment by brunoga** [comment]
I am sorry. I am not sure I understand what you mean here. This library just does deep copies of Go structs.How would a command line tool be useful here? And what is deep-gen?

**Comment by s3rj1k** [comment]
Something like this: https://www.redhat.com/en/blog/kubernetes-deep-dive-code-generation-customresources

Basically a CLI utility that will generate files with DeepCopy() methods.

(Assuming I understood correctly the actual intention usage for this library)

**Comment by brunoga** [comment]
So, for *ANY* type, a DeepCopy() implementation for this library would look like:

```
func (t* T) DeepCopy() *T {
        return deep.MustCopy(t) // This would panic on errors, you can handle them if wanted by calling Copy() instead.
}
```

It does not look like it is worth the effort creating a CLI tool that would simply do that. Or am I missing something?

**Comment by s3rj1k** [comment]
Hmm, I assumed that the library generates the code `not` dynamically, you are correct, no real need but I would appreciate a short README change with the above example, feel free to close the issue, thank you.

**Comment by brunoga** [comment]
Done. Closing.
