### ISSUE TITLE
zero slices are not handled correctly

### ISSUE THREAD

**Issue by kluzzebass** [brunoga/deep#5]
There's a bug in how slices are copied. The zero value of a slice is `nil`, and not an empty slice.

Here's some code that demonstrates the bug:

```
package main

import (
	"encoding/json"
	"fmt"

	"github.com/brunoga/deep"
)

type Blah struct {
	A []int
	B []int
}

func main() {
	lala := Blah{
		A: []int{},
	}

	j, _ := json.MarshalIndent(lala, "", "  ")
	fmt.Println(string(j))

	huhu := deep.MustCopy(lala)

	j, _ = json.MarshalIndent(huhu, "", "  ")
	fmt.Println(string(j))
}
```

Running this code yields the following results:
```
{
  "A": [],
  "B": null
}
{
  "A": [],
  "B": []
}
```

**Comment by kluzzebass** [comment]
I played around with it a bit yesterday, and you only need to add a quick nil-check at the start of the `recursiveCopySlice()` function:

```
if v.IsNil() {
	// If the slice is nil, just return it.
	return v, nil
}
```

The test can be written like this:

```
func TestCopy_Slice_Nil(t *testing.T) {
	var S []int
	doCopyAndCheck(t, S, false)
}
```

**Comment by brunoga** [comment]
Thanks for the report and potential fix. I will apply it soon. Feel free to open a PR next time.
