### ISSUE TITLE
pointer to struct member leads to panic in reflect.Set

### ISSUE THREAD

**Issue by mmp** [brunoga/deep#9]
With the following test code, I get the panic below (distilled from a more complex, real-world use.) The issue is that both `foo` and `foo.N` have the same address; in turn, the `pointers` map maintained by deep stores that address as a `*Foo` when it starts to copy `bar.F`. Then when it tries to process `bar.P`, it founds that it has the same address as `bar.F`, yet its type is `*int` and then `reflect` is unhappy and panics.

I think that a reasonable fix might be to modify `recursiveCopyPtr` to return a `reflect.Value` for pointers it finds in the `pointers` map that have the same type as the given `v`, though I haven't been able to figure out how to get `reflect` to allow me to do that.

```go
func TestTrickyMemberPointer(t *testing.T) {
	type Foo struct {
		N int
	}
	type Bar struct {
		F *Foo
		P *int
	}

	foo := Foo{N: 1}
	bar := Bar{F: &foo, P: &foo.N}

	doCopyAndCheck(t, bar, false)
}
```

```
panic: reflect.Set: value of type *deep.Foo is not assignable to type *int [recovered]
	panic: reflect.Set: value of type *deep.Foo is not assignable to type *int

goroutine 67 [running]:
testing.tRunner.func1.2({0x10422dc60, 0x1400013c330})
	/usr/local/go/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x33c
panic({0x10422dc60?, 0x1400013c330?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
reflect.Value.assignTo({0x104229460?, 0x1400000e818?, 0x104229ba0?}, {0x1041e88a3, 0xb}, 0x104229ba0, 0x0)
	/usr/local/go/src/reflect/value.go:3356 +0x20c
reflect.Value.Set({0x104229ba0?, 0x1400013c328?, 0x14000050c18?}, {0x104229460?, 0x1400000e818?, 0x1e5?})
	/usr/local/go/src/reflect/value.go:2325 +0xcc
github.com/brunoga/deep.recursiveCopyStruct({0x10423cc40?, 0x1400013c310?, 0x14000050cd8?}, 0x14000143e48, 0x0)
	/Users/mmp/deep@v1.2.3/deep.go:224 +0xec
github.com/brunoga/deep.recursiveCopy({0x10423cc40?, 0x1400013c310?, 0x14000050d28?}, 0x1040ec688?, 0xe0?)
	/Users/mmp/deep@v1.2.3/deep.go:74 +0xac
github.com/brunoga/deep.copy[...]({0x1400000e810, 0x1400000e810}, 0x0)
	/Users/mmp/deep@v1.2.3/deep.go:44 +0xf8
github.com/brunoga/deep.Copy[...](...)
	/Users/mmp/deep@v1.2.3/deep.go:11
github.com/brunoga/deep.doCopyAndCheck[...](0x140001376c0, {0x1400000e810, 0x1400000e810}, 0x0)
	/Users/mmp/deep@v1.2.3/deep_test.go:278 +0x64
github.com/brunoga/deep.TestTrickyMemberPointer(0x140001376c0)
	/Users/mmp/deep@v1.2.3/deep_test.go:356 +0x4c
testing.tRunner(0x140001376c0, 0x104256808)
	/usr/local/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x318
FAIL	github.com/brunoga/deep	0.127s
```

**Comment by mmp** [comment]
Thinking about it more, a better fix might be to replace `pointers` with `map[uintptr]map[reflect.Type]reflect.Value`--since you want to be sure to call `recursiveCopy` for the struct. If you encountered the `*int` first, added the new address to `pointers`, and then returned it cast to `*Foo` the second time around, then the `Foo` object wouldn't get the `recursiveCopy` treatment..

**Comment by brunoga** [comment]
Thanks for this bug report. That is really an interesting one and I am pretty sure it will add some overhead to allow solving it. Let me think about it for a bit.

**Comment by brunoga** [comment]
> Thinking about it more, a better fix might be to replace `pointers` with `map[uintptr]map[reflect.Type]reflect.Value`--since you want to be sure to call `recursiveCopy` for the struct. If you encountered the `*int` first, added the new address to `pointers`, and then returned it cast to `*Foo` the second time around, then the `Foo` object wouldn't get the `recursiveCopy` treatment..

I guess that might work. Want to sent a PR? Do run the benchmark after this change just to make sure it will not be too terrible. :)

**Comment by brunoga** [comment]
This has now been fixed. Thanks for reporting it.
